### ISSUE TITLE
Depreciated entry warning

### ISSUE THREAD

**Issue by BeJaHome** [tcarwash/home-assistant_noaa-space-weather#62]
Detected that custom integration 'noaa_space_weather' calls async_forward_entry_setup for integration, noaa_space_weather with title: NOAA Space Weather and entry_id: f7689a7bd288c7c79325b50e0ebff023, which is deprecated, await async_forward_entry_setups instead at custom_components/noaa_space_weather/__init__.py, line 58: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/tcarwash/home-assistant_noaa-space-weather/issues

**Comment by stayneutral** [comment]
Integration fails to load in 2025.6

Error setting up entry NOAA Space Weather for noaa_space_weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/noaa_space_weather/__init__.py", line 55, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by CrewingTop** [comment]
The same problem. Log:

Error setting up entry NOAA Space Weather for noaa_space_weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/noaa_space_weather/__init__.py", line 59, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
